name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make & Debug
      run: make && make debug

    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with: 
      # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Comment to post on an individual's first issue
        issue-message: test issue-message
        # Comment to post on an individual's first pull request
        pr-message: test pr-message
          
