name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make dimanet # make, compile everything
      run: make

    - name: test example1 # might remove and put a example file for test
      run: chmod +x examples/example_1.o && ./example_1.o
