name: Make Strings

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make Strings
      run: make strings
    - name: Make Test Stings
      run: make stringstest
