name: Makefile CI

on:
  push:
    branches: [ "preview" ]
  pull_request:
    branches: [ "preview" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: builddimanet
      run: make && make debug
      
    - name: pingquestionmarkidkwhy
      run: ping github.com
